from centroidal_phi import EESplines, CentroidalPhi
from contact_sequence_wrapper import ContactSequenceWrapper
from spline_utils import polyfitND
from problem_definition import createMultiphaseShootingProblem
